import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// This is how we reference/get our components.
// typically, we put this in the top of our file...
import Hello from '../components/Hello';
import NewConcept from "../components/NewConcept";
import ComponentWrapper from "../components/ComponentWrapper";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <ComponentWrapper textColor={"blue"}>
            <Hello />
            <NewConcept concept={"how to import components"} />
            <NewConcept concept={"how to use props in a component"} />
            <NewConcept concept={"where to put our components in the project"} />
            <NewConcept concept={"how to customize VS Code for productivity"} />
          </ComponentWrapper>
        </main>
      </div>
    </>
  );
}
